### ISSUE TITLE
dpkg: error processing archive clash-nyanpasu_1.4.2_amd64.deb (--install):dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)

### ISSUE THREAD

**Issue by disini** [keiko233/clash-nyanpasu#282]
### 复现步骤 / Step to reproduce

大佬您好，我在ubuntu22.04上尝试了安装，执行命令 dpkg -i clash-nyanpasu_1.4.2_amd64.deb，所有的依赖都已经安装好了，但是试了几次都是这个报错，不知道是什么原因？

```
(Reading database ... 825060 files and directories currently installed.)
Preparing to unpack clash-nyanpasu_1.4.2_amd64.deb ...
Unpacking clash-nyanpasu (1.4.2) ...
dpkg: error processing archive clash-nyanpasu_1.4.2_amd64.deb (--install):
 trying to overwrite '/usr/bin/clash', which is also in package clash-verge 1.3.8
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Processing triggers for bamfdaemon (0.5.6+22.04.20220217-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 clash-nyanpasu_1.4.2_amd64.deb

```

![Screen Capture_select-area_20240120051049](https://github.com/keiko233/clash-nyanpasu/assets/5233769/4b71664f-367e-4e71-8c17-0be876640db3)

### 预期行为 / Expected behaviour

它应该安装好之后出现一个桌面图标

### 实际行为 / Actual Behaviour

实际上它安装完啥也没出来。。。

### 备注 / Addition details

https://github.com/keiko233/clash-nyanpasu/releases/tag/v1.4.2

Releases v1.4.2
Clash Nyanpasu v1.4.2 Latest
Compare
@keiko233 keiko233 released this last month
 v1.4.2
 517e166

[clash-nyanpasu_1.4.2_amd64.deb](https://github.com/keiko233/clash-nyanpasu/releases/download/v1.4.2/clash-nyanpasu_1.4.2_amd64.deb)
57.9 MB
2 weeks ago

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

517e166

### 操作系统及版本 / OS version

Ubuntu 22.04.3 LTS, Gnome 42.9,  Windowsing System X11

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
卸载 clash-verge 即可



发自我的iPhone


------------------ Original ------------------
From: GiGi ***@***.***&gt;
Date: Sat, Jan 20, 2024 5:14 AM
To: keiko233/clash-nyanpasu ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [keiko233/clash-nyanpasu] dpkg: error processing archive clash-nyanpasu_1.4.2_amd64.deb (--install):dpkg-deb: error: paste subprocess was killed by signal (Broken pipe) (Issue #282)





 
复现步骤 / Step to reproduce
 
大佬您好，我在ubuntu22.04上尝试了安装，执行命令 dpkg -i clash-nyanpasu_1.4.2_amd64.deb，所有的依赖都已经安装好了，但是试了几次都是这个报错，不知道是什么原因？
 (Reading database ... 825060 files and directories currently installed.) Preparing to unpack clash-nyanpasu_1.4.2_amd64.deb ... Unpacking clash-nyanpasu (1.4.2) ... dpkg: error processing archive clash-nyanpasu_1.4.2_amd64.deb (--install):  trying to overwrite '/usr/bin/clash', which is also in package clash-verge 1.3.8 dpkg-deb: error: paste subprocess was killed by signal (Broken pipe) Processing triggers for bamfdaemon (0.5.6+22.04.20220217-0ubuntu1) ... Rebuilding /usr/share/applications/bamf-2.index... Processing triggers for mailcap (3.70+nmu1ubuntu1) ... Processing triggers for gnome-menus (3.36.0-1ubuntu3) ... Processing triggers for desktop-file-utils (0.26-1ubuntu3) ... Processing triggers for hicolor-icon-theme (0.17-2) ... Errors were encountered while processing:  clash-nyanpasu_1.4.2_amd64.deb  
Screen.Capture_select-area_20240120051049.png (view on web)
 
预期行为 / Expected behaviour
 
它应该安装好之后出现一个桌面图标
 
实际行为 / Actual Behaviour
 
实际上它安装完啥也没出来。。。
 
应用日志 / App logs
 
No response
 
备注 / Addition details
 
https://github.com/keiko233/clash-nyanpasu/releases/tag/v1.4.2
 
Releases v1.4.2
 Clash Nyanpasu v1.4.2 Latest
 Compare
 @keiko233 keiko233 released this last month
 v1.4.2
 517e166
 
clash-nyanpasu_1.4.2_amd64.deb
 57.9 MB
 2 weeks ago
 
Clash Nyapasu 版本号 / Clash Nyapasu
 
1.4.2
 
是否为 Pre-release / Is pre-release version
 
517e166
 
操作系统及版本 / OS version
 
Ubuntu 22.04.3 LTS, Gnome 42.9,  Windowsing System X11
 
自查步骤 / Verify steps
  
 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request 

 您已仔细查看并知情 Q&amp;A 中的内容 / You have checked Q&amp;A carefully 

 您已搜索过 Issue Tracker，没有找到类似内容 / I have searched on Issue Tracker, No duplicate or related open issue has been found 

 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs 

 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by disini** [comment]
啊！这两个软件冲突吗？

**Comment by disini** [comment]
> 卸载 clash-verge 即可 发自我的iPhone
> […](#)


啊！这两个软件冲突吗？

**Comment by greenhat616** [comment]
你用翻译软件翻译一下那些日记就能得出结论了：clash 由 clash-verge 安装，clash-nypansu 也提供了。因此有冲突，安装失败。

所以有两个解决办法：
1、卸载 clash verge
2、dpkg 加个参数，强制允许 nyanpasu override clash binary。
