### ISSUE TITLE
无法导入订阅链接

### ISSUE THREAD

**Issue by yjplayerhyw** [keiko233/clash-nyanpasu#306]
### 复现步骤 / Step to reproduce

![屏幕截图 2024-01-21 202928](https://github.com/keiko233/clash-nyanpasu/assets/21964839/c6746308-8fc9-4f24-8ee6-1663757e71d2)

### 预期行为 / Expected behaviour

Clash.Verge导入同样链接正常。

### 实际行为 / Actual Behaviour

![屏幕截图 2024-01-21 202928](https://github.com/keiko233/clash-nyanpasu/assets/21964839/26b7c6b0-2a31-498d-bab1-de1d386bc834)

### 应用日志 / App logs

01-22 00:51:19ERROR
Start Mixed(http+socks) server error: listen tcp 127.0.0.1:7890: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

01-22 00:51:19ERROR
External controller listen error: listen tcp 127.0.0.1:9090: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.3

### 是否为 Pre-release / Is pre-release version

1.4.3/1.4.4

### 操作系统及版本 / OS version

Windows11 23H2

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
今日稍晚修复一下这个问题。


现在可以用新建 Profile，选择 remote，修改URL，然后右键不使用代理或者使用内置代理更新来更新订阅。





发自我的iPhone


------------------ 原始邮件 ------------------
From: yjplayerhyw ***@***.***&gt;
发送时间: 01/22/2024, 01:08
To: keiko233/clash-nyanpasu ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
Subject: Re: [keiko233/clash-nyanpasu] 无法导入订阅链接 (Issue #306)





 
复现步骤 / Step to reproduce
 
2024-01-21.202928.png (view on web)
 
预期行为 / Expected behaviour
 
Clash.Verge导入同样链接正常。
 
实际行为 / Actual Behaviour
 
2024-01-21.202928.png (view on web)
 
应用日志 / App logs
 
01-22 00:51:19ERROR
 Start Mixed(http+socks) server error: listen tcp 127.0.0.1:7890: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
 
01-22 00:51:19ERROR
 External controller listen error: listen tcp 127.0.0.1:9090: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
 
备注 / Addition details
 
No response
 
Clash Nyapasu 版本号 / Clash Nyapasu
 
1.4.3
 
是否为 Pre-release / Is pre-release version
 
1.4.3/1.4.4
 
操作系统及版本 / OS version
 
Windows11 23H2
 
自查步骤 / Verify steps
  
 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request 

 您已仔细查看并知情 Q&amp;A 中的内容 / You have checked Q&amp;A carefully 

 您已搜索过 Issue Tracker，没有找到类似内容 / I have searched on Issue Tracker, No duplicate or related open issue has been found 

 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs 

 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
等这个编译完成后，可以试一下最新的开发构建版有没有问题，谢谢！
https://github.com/keiko233/clash-nyanpasu/actions/runs/7610642017

**Comment by greenhat616** [comment]
好像开发版出了些问题，明天晚上我再处理下开发版那个问题吧😂 今天有点累了

**Comment by yjplayerhyw** [comment]
> 好像开发版出了些问题，明天晚上我再处理下开发版那个问题吧😂 今天有点累了

 这下连ui都没有了。。。。😂没法操作·····资源管理器有进程，任务栏有图标（右键无反应无法调出菜单）。。。

**Comment by greenhat616** [comment]
已经确认是哪里出问题了😮‍💨 之前提升鲁棒性的那个提交导致的互斥锁死锁。

**Comment by greenhat616** [comment]
https://github.com/keiko233/clash-nyanpasu/actions/runs/7620961218

等这个编译完成再试一下吧。我叫我朋友帮我提交上去了。

**Comment by yjplayerhyw** [comment]
> https://github.com/keiko233/clash-nyanpasu/actions/runs/7620961218
> 
> 等这个编译完成再试一下吧。我叫我朋友帮我提交上去了。

可以正常使用了
